### PR TITLE
Implements MANIFEST and download of sdssMaskbits.par

### LINKED ISSUE #244: Make setup.py download the latest version of sdssMaskbits.par
In preparation for our own implementation of maskbit handling, we'll want to have a copy of sdssMaskbits.par in the data directory of Marvin. To avoid forgetting to update it every release, let's have it be grabbed by setup.py when we pack a new distribution. This should be easy since the idlutils package is public.

### PR DESCRIPTION
**Pull request by albireox**
This PR slightly changes `setup.py` to use a MANIFEST.in file to specify what non-python files should be added to the distributions. Right now everythin in `python/marvin/data` and `python/marvin/extern` is included, plus a few other files. The switch for including or not the web when packaging is still included in the `setup.py` files given that the MANIFEST does not allow for any kind of conditional input.

Also, when `setup.py` is run the latest copy of sdssMaskbits.par is downloaded and stored in `python/marvin/data`. This fixes #244.

### CODE REVIEW

**Comment by havok2063** [comment]
This looks good to me.  Regarding the maskbits file, this should also work for dev installs as well.  For us, we'll just manually download it I guess?  Should we add this file to our .gitignore?

**Comment by albireox** [comment]
@havok2063 I was planning to keep a copy of the sdssMaskbits under version control in the data directory. Every time we package marvin that file will get updated and we would need to commit it (only if there are real changes to the file), or we can also do it manually if we know the file has changed.

**Comment by havok2063** [comment]
That sounds good to me.  That's less hassle and will ensure we always have at least some version available.

**Comment by albireox** [comment]
Great! Merging ...

**Pull request merged**
