### PR TITLE
NSA display in the web

### PR DESCRIPTION
**Pull request by havok2063**
This adds the display of NSA information into the web, using the Marvin Tools.  The web display now consists of a tabbed display of the SpecMap View and NSA Display.  Clicking the NSA display tab shows a table of parameters and two tabs indicating a Scatter Plot view and a Box-and-Whisker view.   I'm currently only showing two plots and 6 parameters.  The table is loaded when the galaxy page is loaded.  The data for the plots are loaded when the NSA display tab is clicked for the first time.  I grab all the sample data at once for the 6 parameters.  Once it's loaded, no other server call is done for plotting.  Please have a look.   Use MPL-5 for speed, MPL-4 for more sample.

What still needs discussion is how many, and which, NSA parameters do we display in the table?  And how many of those parameters do we allow to be plot-able.   Locally grabbing the MPL-4 sample for 6 NSA parameters took 6 seconds to load the data.  If you could all try playing with it and let me know the server load and page load times.   I have an ngrok open to it, put in Slack.

### CODE REVIEW

**Comment by albireox** [comment]
This looks good to me. I think we want to have a set of parameters (maybe the ones that are already in) that get loaded with the NSA tab, but allow to plots others in the list on demand (i.e., the data would be requested when the user drops the parameter on the axis). I think that in the latter case it's ok for the user to wait a bit. We also nee to evaluate how this scales with ~10,000 galaxies.

That said, I think this is good to merge, and we can add those other changes later.

**Comment by bretthandrews** [comment]
Looks good to me!

A few minor tweaks we could do in the future:
- Can we remove -9999 values (there's one in elpetro_th50_r)?
- Perhaps we should move the legend in the plots further into the upper left.
- Is there a better color (u-r?) for showing SFR?
- I think that we should reverse the magnitude axes so that larger negative mags (brighter objects) are at the top.

**Comment by havok2063** [comment]
* The issue with the -9999 ones is that they are still a valid object, with valid values for the other parameters.  If we remove them, I have to remove them from the entire parameter set, to keep the arrays equal sized.  
 * I think we can make this draggable to solve the problem.  
 * we can include a few colors in the default list, the rest can be grabbed in post
 * yeah that was in the forgotten list of things to do

I've decided before I merge to play around with the violin plots.  I'm getting way too excited about d3 and information visualization.

**Comment by albireox** [comment]
Can you remove the -9999 only when you are going to display that specific parameter? That way you can still receive them from the server but not plot them locally.

**Comment by havok2063** [comment]
Yeah, I can remove it every time that plot is generated.

**Comment by havok2063** [comment]
I've added in the changes from the 4 bullet points.  I've expanded the number of parameters to 12.  I'm still trying to get them in the right order.  Retrieving my MPL-4 sample data for all 12 parameters takes the same time as before, ~5 seconds.  So I haven't done anything with the 5 default plot-able + extra on demand.  Can y'all check the data loading times on your end?

**Pull request merged**
