### PR TITLE
Improvements to Marvin authentication and access toggling for DR15

### PR DESCRIPTION
**Pull request by havok2063**
This PR implements improvements needed for DR15.  It now includes toggling between public and collaboration access modes, and an improved authentication system for the web and the API.  This PR coincides with changes in the Brain, master branch.  See https://github.com/sdss/marvin_brain/commits/master/python/brain, commits 112b522 through 2b90897

- new config access variable (`public`, and `collab`)
- MPL-7/DR15 datamodel compliant
- Flask-Login for web authentication
- Flask-JWT-Extended for API token authentication

I have moved the netrc handling into the Brain, which now reads in, and checks all entries in the netrc file for all hosts defined in the Brain.  Marvin now has an access mode which provides people with access either to DR releases or DR+MPL releases.  To switch to `collab` mode, the user must have a valid netrc file.  

Marvin now always uses its built-in tree and overrides any prior user environment.  When toggling between MPLs and DRs, or between DRs, Marvin uses the tree to set the new SAS_BASE_DIR paths for files.  There is now a public and collab API sasurl, which Marvin sets when accessing either a DR or MPL.  These urls will point to either the public Marvin server or the collaboration Marvin server.  There's a new contextmanager, `config._replant_tree` which runs every time a release is changed to assess what access mode, release, and paths need to be updated.  

It now also includes a default `marvin.yaml` config file and a user one, in `~/.marvin/marvin.yaml`.  These will get combined and used to set some `marvin.config` variables or procedures. 

Marvin now uses Flask-JWT-Extended for API authentication.  JWT is JSON-Web-Token and is the standard method for token-based API authentication.  To use the Marvin API and make any remote calls, the user needs a valid fresh authentication token, and must login to retrieve one, using a new `config.login` method.  A valid login is through a valid host, username, and password in their netrc file.  The current default timeout for a fresh token is 15 minutes.  We can probably up this to an hour.  

Marvin web now uses Flask-Login for web authentication.  It will accept either the sdss login or the trac username login.  The web defaults to public mode, not logged in, with only DRs.  Once the user logs in, in the upper right, they have access to MPLs.  

There is now a new, minimal, User table and model in the history schema of the mangadb.  This records every login by a unique user, but it is not well developed or complete.  

I'm still working on fixing the tests, but I'd like people to review the code, and maybe start trying it out.  I think I've got it mostly working but I'm sure I've missed something.  If you have questions or find problems, let me know.

### CODE REVIEW

**Comment by albireox** [comment]
Merged! 😢 I don't know what I'm going to do without this PR as a constant in my GH notifications.

Great work!

**Comment by bretthandrews** [comment]
Tis a sad day indeed. Well done!

**Comment by havok2063** [comment]
I can create a new PR with the same name that just constantly touches every file to change timestamps in the headers.  And leave it as a reminder of what once was.

**Comment by albireox** [comment]
I just wouldn't be the same. All good things must come to an end. It's the way life works.

**Pull request merged**
