### PR TITLE
Improve installation documentation

### LINKED ISSUE #104: Problem with Matplotlib following installation of Marvin on MacOS
I installed Marvin on two different MacOS machines. During installation marvin installs a new version of matplotlib for no apparent reason. Here's the extract from the installation terminal

Collecting matplotlib>=1.5.3 (from sdss-marvin)
  Downloading matplotlib-1.5.3-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (11.2MB)

after this, matplotlib stops working and I get the following warning if I load it in python

Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ

I found a solution which fixes the problem here

http://stackoverflow.com/questions/21784641/installation-issue-with-matplotlib-python

It would be good to either document this failure mode on the Marvin installation page or, better, to fix it.
Btw, I get the same problem on my MacBookPro running Mavericks and on my iMac running OS 10.8. In both computers I use an Anaconda installation of python.

### PR DESCRIPTION
**Pull request by albireox**
This pull request includes some improvements to the documentation, mostly to the installation sections. These follow some discussions in Shanghai. In particular:

- The index page has been slightly reordered.
- The installation page has been tidied up. The old installation instructions have been removed, as they were now obsolete.
- Added a section about the SDSS dependencies (tree, brain, sdss_access).
- Added a section about the local SAS directory structure and the environment variables that define it.
- Added a section with FAQs and known issues in the installation.

Before we merge this, please check the text and commit changes. In particular, consider adding more text to the section about how to test that marvin has been correctly installed and more FAQs.

Fixes #104.

### CODE REVIEW

**Comment by havok2063** [comment]
I had started my own rewrite of this page.  I will look through what you have and suggest edits.  Before we merge.   Or just edit afterward.   I've also been editing the Jupyter notebook section.

**Comment by albireox** [comment]
Sounds good to me. I was thinking that maybe we want to make the FAQs its own page, and expand its scope beyond installation. I'm specifically thinking about the problems with cookies which is not exactly an installation problem but that we should include there.

**Comment by havok2063** [comment]
Yeah an FAQ page is a good idea.

**Comment by albireox** [comment]
Ok, I've created a standalone FAQ section.

**Comment by havok2063** [comment]
I've pushed my local installation changes into your install_faq branch.  I'm ready for this to be merged and then I will merge some additional Jupyter notebook tutorial changes.  Can you add your Shanghai Tools notebook into the notebook folder so I can access it?

**Comment by albireox** [comment]
Thanks for the extra FAQs, they look good. I've added the Shanghai tools notebook and linked it. Let me know when you are finished making changes and I'll merge this.

**Comment by havok2063** [comment]
I have added and pushed the Shanghai query notebook into the tutorials.  I'm more or less done and am ready for you to merge.

**Comment by albireox** [comment]
Sounds good. I'll merge and rebuild the documentation at Utah.

**Pull request merged**
