### PR TITLE
Mapplot

### LINKED ISSUE #255: Change code block styling for lean tutorial to regular python
Using the ipython code block styling in the lean tutorial causes the code to actually run when readthedocs builds the documentation. However, this fails, so the output is garbled.

### PR DESCRIPTION
**Pull request by bretthandrews**
### Added:
- Issue #253: Plotting tutorial.
- Issue #223: Easy multi-panel map plotting (with correctly placed colorbars).
- Issue #232 and Issue #251: Uses matplotlib style sheets context managers for plotting (map, spectrum, and BPT) and restores previous defaults before methods finish.
- Issue #189: Map plotting accepts user-defined value, ivar, and/or mask (including BPT masks).
- Issue #252: Quantile clipping for properties other than velocity, sigma, or flux in web.

### Changed:
- Issue #241: Moved map plotting methods from tools/map to utils/plot/map
- Issue #229 and Issue #231: Switch to new gray/hatching scheme (in tools and web):
  - gray: spaxels with NOCOV.
  - hatched: spaxels with bad data (UNRELIABLE, MATHERROR, FITFAILED, DONOTUSE) or S/N below some minimum value.
  - colored: good data.
- Issue #238: Move plot defaults to datamodel (i.e., bitmasks, colormaps, percentile clips, symmetric, minimum SNR).
- Issue #206: SNR minimum to None (effectively 0) for velocity maps so that they aren't hatched near the zero velocity contour.
- Simplified default colormap name to "linearlab."
- Decreased map plot title font size in web so that it does not run onto second line and overlap plot.

### Fixed:
- Fixed #255: Lean tutorial code cells did not work with the ipython directive, so they now use the python directive.
- Highcharts draggable legend cdn.

### Removed:
- Issue #232 and Issue #251: Automatic setting of matplotlib style sheets via seaborn import or plt.style.use.

### CODE REVIEW

**Comment by bretthandrews** [comment]
Suggestions from @havok2063:
**Code**
- [ ] Are bitmasks the same for MPL-4 and MPL-5?
- [ ] Rename `utils.plot.map.make_image` as `utils.plot.map.select_good_spaxels.`
- [ ] Setting the matplotlib hatch color and linewidth might not work in matplotlib versions <= 1.5.

**Documentation**
- [ ] Plotting tutorial:
  - [ ] Rename "Map Using BPT Mask" section as "Plot Halpha Map of Star-forming Spaxels."
  - [ ] Add hatched regions to plot of Halpha flux in star-forming spaxels?
  - [ ] Add a few more comments to plotting tutorials code (e.g., why ~mask in BPT).
  - [ ] Add links to other tutorials for fuller explanations.
- [ ] Thoroughly document that stellar velocity maps do not use a minimum SNR.
- [ ] Create documentation page for utils.plot.map in the style of the [astropy.table](http://docs.astropy.org/en/stable/table/index.html) documentation.

**Comment by bretthandrews** [comment]
**Code**
- [ ] Add plotting function for Maps that implements something similar to the example code given in the Multi-panel Plot section of the plotting tutorial.
  - [ ] By default, show the three default maps (stellar vel, Ha flux, D4000).
  - [ ] Optionally take in a map grouping keyword to show a pre-defined set of maps (e.g., `"kinematics"` would correspond to `stellar_vel` and `stellar_sigma`).
  - [ ] Optionally accept a list of maps to display.

**Documentation**
- [ ] Provide example code to make a multi-panel plot of the same property(ies) for several galaxies.

**Comment by havok2063** [comment]
The feature in your last comment I would drop to low priority.  This PR is becoming dangerous on feature creep and we're supposed to be focused on testing and hitting our DR15 requirements and goals, with no new features.  I know refactor of the map plotting was in there, but I think you've hit that already.  And for all the DR15 "features" we should scope out what they actually entail, so the scope does not grow too large.

**Comment by bretthandrews** [comment]
OK, the `Maps.plot()` isn't a necessity for this PR, but I view it as an important feature that is trivial to implement (i.e., I've already done it for the plotting tutorial and just need to wrap it), so I am going to try to do it on my own time.

**Comment by havok2063** [comment]
I agree with you there.  Maybe separate it out into its own issue.  If you think it's quick and easy to implement then by all means.  And if you're done with it before we merge and release this PR then you can include it.  I'm just worried about feature creep.  This PR went from fixing a few map plotting bugs to refactoring map plotting now to add in brand new maps plotting.  It's a rabbit hole where we'll always find new things we want to implement.  I mean after this the next thing would be a utility function that accepts a property+channel, and a list of plateifus and does a multi-panel plot of that property over the list.  The hole just goes deeper and deeper. And at some point just turns into writing matplotlib code for the user.

**Comment by bretthandrews** [comment]
Brilliant idea! I'm on it!

**Comment by havok2063** [comment]
doh!

**Comment by kruksandor** [comment]
I get an import error (ImportError: No module named 'marvin.utils.plot.map') when trying to import mapplot.

**Comment by havok2063** [comment]
Hi Sandor,

Did you upgrade to the latest version of Marvin, which is 2.1.3?  That module referenced in the error is a new package that was added in the latest version of Marvin.  I see that you're using Marvin 2.1.2. 

You can check what version you have by starting ipython and typing
```
import marvin
marvin.__version__   
```
If you need to upgrade, just do `pip install --upgrade sdss-marvin`

**Comment by kruksandor** [comment]
Yes, it does work now on 2.1.3, that was the issue. Thanks!

I installed Marvin only one or two days ago, is the version on pip install sdss-marvin not the latest?

**Comment by bretthandrews** [comment]
Actually, we just pushed v 2.1.3 to PyPI (pip) yesterday, so just unfortunate timing. Thank you for reporting the issue, though!

**Pull request merged**
