### PR TITLE
Fixes windows compatibility issues

### PR DESCRIPTION
**Pull request by bretthandrews**
- Handles importing `pwd` in Windows
- gets $HOME dir in Windows

### CODE REVIEW

**Comment by bretthandrews** [comment]
Fixes #397

**Comment by albireox** [comment]
Is `winpwd` a system package in Windows or is it an external dependency? If the latter it should be added to the requirements. If not, this looks good to me.

**Comment by bretthandrews** [comment]
After looking into it a little more, I'm gonna need to check this fix.

**Comment by havok2063** [comment]
This PR is no longer needed after #652

**Pull request closed without merging**
