### PR TITLE
Fixes hybrid colours in SampleModelClasses

### LINKED ISSUE #117: NSA hybrid colours are egregiously wrong
As referenced in #108, the colours we calculate as hybrid properties/method in the NSA ModelClasses (e.g., `petroth50_el_r_g`) are calculated assuming that `petroth50_el` are magnitudes, when they are half-light radii.

We need to fix this by using `petroflux_el` and calculating the asinh magnitudes (I think those are the ones we want) for each band. Probably we want to create two types of hybrid properties (and corresponding hybrid methods):

- `petromag_el_X` containing the asinh magnitudes from `petroflux_el`.
- `petromag_el_X_Y` containing the colours (which, at this point would just be the difference of two `petromag_el_X`)

### PR DESCRIPTION
**Pull request by albireox**
This PR fixes #117. It now correctly uses `elpetro_flux` to derive the asinh magnitudes as hybrid properties (now called `elpetro_mag_X`) and the colours (both as `elpetro_colour(bandA, bandB)` or as `elpetro_mag_X_Y`).

A couple potential issues:

- Right now, both magnitudes and colours exclude F and N (from Galex) as I haven't been able to find softening parameters for those bands to convert them to asinh magnitudes. We could add them as Pogson magnitudes, but that sounds a bit confusing. Unless somebody knows how to calculate asinh mags for Galex bands.

- We could, in principle, have `elpetro_mag` as an array instead of `elpetro_mag_X`. The disadvantage is that, because of the previous point, the array would have five elements while all other magnitude and flux arrays have seven.

### CODE REVIEW

**Comment by havok2063** [comment]
The first point might be a question for the sdss-archive mailing list?  Or Mike, since he put together the NSA catalog.  For the second point, I think I prefer elpetro_mag_X since it makes it a bit easier to query on or access.   A few other areas to modify with regards to the new color names ...

in query/forms.py
```
    def _init_name_shortcuts(self):
        ''' initialize the name shortcuts '''
        self._nameShortcuts = {'haflux': 'emline_gflux_ha_6564',
                               'g_r': 'petroth50_el_g_r'}
```
Also, the query parameters need to be updated in the documentation as well as in the notebooks where g-r is mentioned (I think just Shanghai-Demo-Queries).  Additionally, we should write some tests for a color query and/or accessing it from the form, but this probably deserves a fuller conversation on rewriting the query tests to be stable across all our dbs.

**Comment by albireox** [comment]
I have modified the shortcut and the documentation. The file `query_params.rst` will need to be regenerated once we fix the sample db and we get the `elpetro` columns instead of `petro_el`. Queries seem to work, but I'm not able to run the tests with my version of the DB. You may want to double check that.

**Comment by havok2063** [comment]
Ok.  I say go ahead and merge.  I can write a test query using g-r since we don't one yet.  I suppose this means I'll to regenerate my db tables.

**Comment by albireox** [comment]
Ok, merging this.

**Comment by havok2063** [comment]
Are we going to ask about the Galex magnitudes?

**Pull request merged**
