### PR TITLE
New bin class

### PR DESCRIPTION
**Pull request by albireox**
This pull request includes changes to `Spaxel` and implements the new `Bin` class. `Spaxel` has now been modified to only represent spaxels from unbinned maps/modelcubes. This can be overridden using the `allow_binned=True` parameter, but it's not the default behaviour. This change does not seem to have broken anything, but any additional test would be good, as a fair amount of things depend on `Spaxel`.

`Bin` is still a pretty basic implementation but it contains all the critical bits, and can be extended after the beta release.

### CODE REVIEW

**Comment by havok2063** [comment]
Can you add/update all the necessary documentation with text for this class, usage, etc?

I've had a look through your changes and everything seems good to me.  It doesn't look like anything is egregiously off.  And it's good to know Travis runs on pull requests now.  I think we can ignore the failures until we sort out the testing issues.

**Comment by albireox** [comment]
Done. I also added the ModelCube and the Bin to the documentation and added a method to load all the spaxels in a Bin at once.

**Comment by havok2063** [comment]
Ok.  Sounds good.  We probably need more descriptor documentation for the tools or tutorials, but that shouldn't stop us from merging this in.

**Comment by albireox** [comment]
Yes, this is a basic documentation, but should suffice for now.

**Pull request merged**
