### PR TITLE
Enable Map Arithmetic

### PR DESCRIPTION
**Pull request by bretthandrews**
This PR enables map addition, subtraction, multiplication, and division. It correctly propagates ivar and handles the combination of other map attributes (including masks).

### CODE REVIEW

**Comment by albireox** [comment]
This looks good to me, and a nice addition. Are you sure we need the deepcopy of the Map? That is likely to make arithmetic operations less efficient, but I haven't dug enough in the code to know for sure.

This would require some refactoring to be merged with the refactoring I'm doing of several of my previous refactorings, but it's good to have this now so that we can blend it.

**Comment by bretthandrews** [comment]
If we don't use `deepcopy`, then it would overwrite one of the original maps. Also, the reason for defining a `__deepcopy__` method specifically was that `deepcopy` uses `__getstate__` if there is no `__deepcopy__` method. In `MarvinToolsClass`, `__getstate__` returns an error for DB objects (to prevent saving/pickling.

**Comment by havok2063** [comment]
This all looks good to me.  Can we switch to merge into one of José's branches?  It sounds like your stuff and his new stuff can be combined.

**Comment by bretthandrews** [comment]
The changes have already been merged into `new_datamodel_arith`, so I'm just gonna close this PR.

**Pull request closed without merging**
