### PR TITLE
Maskbits: fix case when none of the labels exist in the maskbit

### LINKED ISSUE #507: Better exception message when mask bit does not contain a label
**Describe the bug**
As described in #505, when trying to get the mask for a mask bit label that does not exist for that maskbit, the error is not very clear.

**To Reproduce**
```
In [5]: cb = marvin.tools.cube.Cube('8485-1901')

In [6]: skybad = cb.pixmask.get_mask('SKYSUBBAD')
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-6-77e2c435becf> in <module>()
----> 1 skybad = cb.pixmask.get_mask('SKYSUBBAD')

~/Documents/Repo/manga/marvin/python/marvin/utils/general/maskbit.py in get_mask(self, labels, mask, dtype)
    374         assert dtype in [int, bool], '``dtype`` must be either ``int`` or ``bool``.'
    375
--> 376         bits = self.labels_to_bits(labels)
    377         mask = mask if mask is not None else self.mask
    378         return np.sum([mask & 2**bit for bit in bits], axis=0).astype(dtype)

~/Documents/Repo/manga/marvin/python/marvin/utils/general/maskbit.py in labels_to_bits(self, labels)
    337             [0, 1]
    338         """
--> 339         return self.values_to_bits(self.labels_to_value(labels))
    340
    341     def get_mask(self, labels, mask=None, dtype=int):

~/Documents/Repo/manga/marvin/python/marvin/utils/general/maskbit.py in labels_to_value(self, labels)
    315             labels = [labels]
    316
--> 317         bit_values = [self.schema.bit[self.schema.label == label].values[0] for label in labels]
    318         return np.sum([2**value for value in bit_values])
    319

~/Documents/Repo/manga/marvin/python/marvin/utils/general/maskbit.py in <listcomp>(.0)
    315             labels = [labels]
    316
--> 317         bit_values = [self.schema.bit[self.schema.label == label].values[0] for label in labels]
    318         return np.sum([2**value for value in bit_values])
    319

IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Expected behavior**
A cleaner message.

### PR DESCRIPTION
**Pull request by albireox**
Fixes #507

This pull request:
- [X] Has a title that summarises what is changing.
- [ ] Updates the documentation accordingly.
- [x] Has unit tests & [code coverage](https://coveralls.io/github/sdss/marvin) is not adversely affected (within reason).
- [ ] Works with Python 2.7 and 3.6 (and ideally with Python 3.7).
- [X] Updates the [CHANGELOG](https://github.com/sdss/marvin/blob/master/CHANGELOG.rst).
- [ ] Removes more lines of code than it adds.
- [ ] If relevant, adds a new entry to the [What's new?](https://github.com/sdss/marvin/blob/master/docs/sphinx/whats-new.rst) page.

### CODE REVIEW

**Comment by bretthandrews** [comment]
I would argue that the desired behavior here should be to throw an error (and a more descriptive one) instead of returning a mask with all of the bits set to 0.

For example, in #505 @YiqingLiu was trying to get a mask for `SKYSUBBAD` from `cb.flux.pixmask

**Comment by bretthandrews** [comment]
Sorry misclick.

**Comment by bretthandrews** [comment]
I would argue that the desired behavior here should be to throw an error (and a more descriptive one) instead of returning a mask with all of the bits set to 0.

For example, in #505 @YiqingLiu was trying:
```
skybad = cb.pixmask.get_mask('SKYSUBBAD')
```
however, returning a mask of all zeros would indicate that there are no pixels with a bad sky subtraction, which may or may not be true.  We should warn users that the label that they tried to get a mask for is not in the mask that they thought (in this case the `SKYSUBBAD` label is in `MANGA_DRP3QUAL` accessible via `cb.quality_flag`).

**Comment by havok2063** [comment]
Since today is when we're supposed to have all code in place, I'd like to have this merged before the DevCon on Monday so we can tell Anne-Marie we're focusing only on documentation and server configuration.

**Comment by albireox** [comment]
Sorry for the delay. I think this is ready to merge. I added a check in case one of the labels passed to `get_mask` is not the the list of schema labels. If so, it raises a clear error message.

**Pull request merged**
