### PR TITLE
NSA fix for 7443

### LINKED ISSUE #129: Plate #7443 breaks Marvin API? (http 500)
When I ran the online example of API using the plate #7443 (and only this plate), I got an HTTP Status Error: 500. Maybe as a commisioning plate, it has something special that breaks Marvin.

The example/code I used:
```
from marvin import config
config.mode = 'remote'
from marvin.api.api import Interaction
plateifu = '7443-12701'
url = config.urlmap['api']['getCube']['url']
response = Interaction(url.format(name=plateifu))
```
The Error message:
marvin-api http 500

### PR DESCRIPTION
**Pull request by albireox**
This PR removes the automatic loading of redshift in `Cube` to avoid problems with galaxies not in the NSA (e.g., 7443-12701 reported in #129).

The key is that we want this change to not break backwards compatibility with the API for previous versions of Marvin. The API side of `getCube` now check whether it can grab the NSA information and, if it cannot, it returns `redshift=-1`. If the NSA is available it returns `cube.nsa.z` (this will not be used by marvin>=2.1, but it will for previous versions).

In `Cube` I have removed all loading of redshift. The redshift should now be accessed via `cube.nsa.[z/redshift]`.

I have added a few tests for 7443-12701 and tried to test it in an order such that I think it will work when Utah is running 2.1 and an user is running 2.0.9. But we should check that again before releasing.

On a related note, at some point we (i.e., probably me) decided that if we load a cube from a file the NSA data would be grabbed form the DRPall, while if it was form DB or API it would be gotten from the NSA table in the DB (or via a call to the remote which would use the DB). This was, in principle, for consistency, so that if you are working locally you'd get all local results. An issue now is that if you load 7443-12701 from file you do get a `cube.nsa` attribute with data (from the DRPall) but if you load it from the DB or API `cube.nsa=None`. We may want to rethink this at some point.

Fixes #129

### CODE REVIEW

**Comment by havok2063** [comment]
`If the NSA is available it returns cube.nsa.z (this will not be used by marvin>=2.1, but it will for previous versions).`  Why won't this be used for marvin >= 2.1?  

Why does 7443-12701 have NSA information in the drpall file but not in the db?  Shouldn't they be consistent?

**Comment by albireox** [comment]
It won't be used in 2.1 because we have removed the `cube.redshift` attribute. So, the API call will return `redshift` in the dictionary, but it won't be used.

-9999 Is ok. I've just done it.

Actually, I checked and 7443-12701 IS in the NSA catalogue, only that because its mangaid is `12-XXXX` I guess the DB loading script failed to link it to the right row in NSA v1_0_1. In the DRPall file it is ok because that information comes from `plateTargets-12`, which is up to date and contains the NSA info.

In general, I think it is ok to have this inconsistency for galaxies that are not NSA (e.g., certain ancillaries). For this particular case(s), we should fix it in the DB.

**Comment by havok2063** [comment]
I also had the same problem when trying to access 7495-1901 over the API.  This fix should now fix all those cases where the cubes aren't linked to any NSA targets.  That's odd about the db loading script.  I'll look into it.  I wonder how many galaxies are in there that aren't connected to their target.

**Comment by albireox** [comment]
Yeah, at some point we should consider adding other catalogues/plateTargets. For now, I think it should only affect 7443 and 7495 (the plates in plateTargets-12). Those are the only ones that ARE NSA but are probably not linked there because of the loading script.

**Pull request merged**
